version: "3.9"
services:
  web:
    build: .
    ports:
      - '3000:80'
  mongo:
    # container_name: mongo
    image: mongo
    volumes:
      - ./docker_volumes/mongo:/data/db
    ports:
      - '27018:27017'
